# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.6"
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env create --file environment.yml --name pyda_env
    - name: Lint with flake8
      run: |
        # stop if there are Python syntax errors or undefined names
        source activate pyda_env
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        source activate pyda_env
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/pyDA_utils/
        echo $PYTHONPATH
        cd ./tests
        pytest --ignore=./data --ignore=./test_create_ob_utils.py --ignore=./test_ensemble_utils.py
